// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivyhfjeovkbutpdvghom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2eWhmamVvdmtidXRwZHZnaG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTY1ODcsImV4cCI6MjA2NjI3MjU4N30.vZoQylqFmAYEOhMrge3gMCoiKK2EN2QnK8kTF11PJzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);